version: '3.8'

services:
  database_todo:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=power5
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    build:
      dockerfile: Dockerfile
      context: ./packages/server
      target: dev
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - NODE_ENV= development
      - DEBUG= nodejs-docker-express:*
    ports:
      - 3333:3333
    links:
      - database_todo
    depends_on:
      - database_todo

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./packages/web
    volumes:
      - /app/node_modules
      - ./packages/web:/app

networks:
  back:

volumes:
  postgres: {}
