version: '3.8'

services:
  database_todo:
    image: postgres
    container_name: database_todo
    # restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=power5
      - POSTGRES_DB=dbTodo
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - pgdata:/data/postgres

  app:
    container_name: todo_app
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/usr/src
    command: npm run dev2
    # restart: always
    ports:
      - 3333:3333
      - 9229:9229
    environment:
      - NODE_ENV= development
      - DEBUG= nodejs-docker-express:*
    links:
      - database_todo
    depends_on:
      - database_todo

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
    driver: local
