version: '3.7'

services:
  database_todo:
    image: postgres
    container_name: database_todo
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=power5
      - POSTGRES_DB=dbTodo
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: todo_app
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/user/src/app:consistent
    links:
      - database_todo
    depends_on:
      - database_todo

volumes:
  pgdata:
    driver: local
